# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false 

[directory]
truncation_symbol = '/î° /'
truncation_length = 4
truncate_to_repo = false
home_symbol ='ï€… ' 

[shell]
disabled = false
nu_indicator = "nu"
zsh_indicator = ""

[custom.windowscheck]
when = 'test "${PWD##/mnt/c/}" != "${PWD}"'
symbol = " î˜ª "

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = ' [âœ¦](bold #9b7fd6) ' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
[rust]
format = 'via [ğŸ¦€ $version](red bold)'
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

